/**
 * The public GraphQL schema, and the only place its SDL is written.
 *
 * `schema.graphql` at the repository root is generated from the constant
 * below by `npm run graphql:schema`, and `test/graphql-schema.test.ts` fails
 * if the two fall out of step. That root file is what the iOS and Android
 * clients generate their types from, so a schema change that never reaches it
 * is a change the apps compile against a stale copy of.
 *
 * Scope: reading one product's add-on configuration. Building a cart is the
 * Storefront API's job — this schema hands over the variant ids to put in it.
 */

import { buildSchema, type GraphQLSchema } from "graphql";

/**
 * Prepended to the generated schema.graphql. A GraphQL comment, so the file
 * stays valid SDL that Apollo iOS and Apollo Kotlin can read as-is.
 */
export const SCHEMA_FILE_HEADER = [
  "# Generated by `npm run graphql:schema` from app/graphql/schema.ts.",
  "# Do not edit this file by hand.",
  "",
  "",
].join("\n");

export const SCHEMA_SDL = `
"""
Add-on configuration for the Product Add-ons app.

Served over the Shopify app proxy at
https://<shop-domain>/apps/product-addons/graphql, so requests are signed and
verified by Shopify. There is no API key to ship inside a mobile binary; a
client needs only the shop's own domain.
"""
schema {
  query: Query
}

type Query {
  """
  The add-on groups that apply to one product, in display order.

  Returns an empty configuration rather than an error when the product has no
  add-ons, when the id does not parse, or when the app is not installed on the
  shop. A product screen should render without add-ons, not fail.

  Ids may be given either as bare numbers (7241...) or as GIDs
  (gid://shopify/Product/7241...), whichever form the caller already holds.
  """
  addonConfig(
    productId: ID!

    """
    The collections the product belongs to. The caller passes these because it
    already knows them, which keeps this to a single indexed database read with
    no Admin API call. Omit them and groups targeted at a collection will not
    match.
    """
    collectionIds: [ID!]
  ): AddonConfig!
}

type AddonConfig {
  "ISO 4217 currency of every price in this configuration, for example USD."
  currency: String!

  "Empty when no group applies to the product."
  groups: [AddonGroup!]!
}

type AddonGroup {
  id: ID!

  "Customer-facing heading. Falls back to the group's internal name."
  heading: String!

  "Whether the customer may choose more than one option in this group."
  selection: AddonSelection!

  """
  Purchasable add-ons. Each is backed by a real product variant, which is what
  makes the displayed price the price Shopify charges. Never contains an option
  without a variant.
  """
  options: [AddonOption!]!

  "Free-text and choice inputs, collected as line item properties."
  fields: [AddonField!]!
}

enum AddonSelection {
  "Any number of options, including none."
  MULTI

  "At most one option."
  SINGLE
}

type AddonOption {
  id: ID!
  title: String!
  description: String

  """
  Price in the smallest currency unit (cents for USD). An integer, so a client
  can total it without floating point drift. Zero is a free add-on, which is
  still added to the cart as a variant.
  """
  priceCents: Int!

  """
  Variant GID, for building a cart through the Storefront API — pass it as the
  merchandiseId of a cartLinesAdd line.
  """
  variantGid: ID!

  """
  The same variant as a bare number, for the AJAX cart (/cart/add.js) and
  anything else that takes a legacy id.
  """
  variantId: ID!
}

type AddonField {
  id: ID!
  label: String!
  type: AddonFieldType!

  "When true, the customer must supply a value before adding to cart."
  required: Boolean!

  placeholder: String
  helpText: String

  "The choices to present. Non-empty only when type is SELECT."
  choices: [String!]!

  """
  Maximum accepted length, when the merchant set one. Shopify truncates a line
  item property at 255 characters regardless, so clients should cap there too.
  """
  maxLength: Int
}

enum AddonFieldType {
  TEXT
  TEXTAREA
  SELECT
  CHECKBOX
  DATE
  NUMBER
}
`.trimStart();

let cached: GraphQLSchema | null = null;

/**
 * Parsing SDL is not free and the schema never changes at runtime, so it is
 * built once per process rather than once per request.
 */
export function addonGraphQLSchema(): GraphQLSchema {
  if (!cached) {
    cached = buildSchema(SCHEMA_SDL);
  }
  return cached;
}
